#!/usr/bin/env python3
"""
emit_facts.py — regenerate every number this project quotes.

Two of the five documented mistakes in this project were the same mistake: a
count got written into prose, the prose outlived the data, and nobody could tell
which number was current. The Western Civilization set carries four different
figures across four documents. The undergraduate harvest carries two.

The rule that prevents it is mechanical rather than careful. No number appears in
a document. Documents cite this file, and this file is regenerated by a command.

Writes out/FACTS.md and out/facts.json. Run it at the end of every pipeline.

Usage
-----
    python3 scripts/emit_facts.py --in out/fstem_repository_scored.jsonl
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from collections import Counter
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from fstem_common import RUNGS, read_jsonl, log  # noqa: E402

ROOT_PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate every quotable number.")
    ap.add_argument("--in", dest="infile", required=True)
    ap.add_argument("--out", default=os.path.join(ROOT_PKG, "out"))
    args = ap.parse_args()

    recs = read_jsonl(args.infile)
    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    cmd = f"python3 scripts/emit_facts.py --in {args.infile}"

    by_rung = Counter(r["rung"] for r in recs)
    by_source = Counter(r["source_type"] for r in recs)
    by_contrib = Counter(st for r in recs
                         for st in (r.get("contributing_sources") or [r["source_type"]]))
    by_vertical = Counter(v["vertical"] for r in recs for v in r["verticals"])
    by_thread = Counter(t for r in recs for t in r["threads"])
    flags = Counter(f for r in recs for f in r.get("extraction_flags") or [])
    held = sum(1 for r in recs if (r.get("ocw") or {}).get("held"))
    unheld = sum(1 for r in recs if (r.get("ocw") or {}).get("held") is False)
    unscored = sum(1 for r in recs if not r["verticals"])
    multi = sum(1 for r in recs if len(r["verticals"]) >= 3)
    overlaps = sum(1 for r in recs if "cross_corpus_overlap" in (r.get("extraction_flags") or []))
    level_unknown = sum(1 for r in recs if not r.get("level_stated"))

    facts = {
        "generated_at": stamp,
        "source": os.path.abspath(args.infile),
        "command": cmd,
        "total_assets": len(recs),
        "by_rung": dict(by_rung),
        "by_source_type": dict(by_source),
        "by_contributing_source": dict(by_contrib),
        "by_vertical": dict(by_vertical),
        "by_thread": dict(by_thread),
        "held": held,
        "harvest_required": unheld,
        "unscored": unscored,
        "multi_vertical_3plus": multi,
        "cross_corpus_overlaps": overlaps,
        "level_not_stated": level_unknown,
        "flags": dict(flags),
    }

    L = ["# FSTEM Facts", ""]
    L.append(f"Generated {stamp} from `{os.path.abspath(args.infile)}`.")
    L.append("")
    L.append(f"Regenerate with:  `{cmd}`")
    L.append("")
    L.append("Every number this project quotes lives here. Documents cite this file. "
             "A figure written into prose anywhere else is provisional until it appears in this table.")
    L.append("")

    L.append("## Headline")
    L.append("")
    L.append("| Fact | Value |")
    L.append("|---|---|")
    L.append(f"| Total teaching assets | {len(recs)} |")
    L.append(f"| Held on disk | {held} |")
    L.append(f"| Named but not harvested | {unheld} |")
    L.append(f"| Level not stated anywhere | {level_unknown} |")
    L.append(f"| Unscored, too little text | {unscored} |")
    L.append(f"| Claimed by three or more verticals | {multi} |")
    L.append(f"| Cross-corpus overlaps resolved | {overlaps} |")
    L.append("")

    L.append("## By rung")
    L.append("")
    L.append("| Rung | Grades | Verb | Assets |")
    L.append("|---|---|---|---|")
    for rung, meta in RUNGS.items():
        L.append(f"| {rung} | {meta['grades'][0]}–{meta['grades'][1]} | {meta['verb']} | {by_rung.get(rung, 0)} |")
    L.append("")

    L.append("## By source harvest")
    L.append("")
    L.append("Two columns, because they answer different questions. `Winner` counts assets whose "
             "merged record came from that harvest. `Contributed` counts every asset the harvest "
             "touched, including those it merged into. A harvest that duplicates existing courses "
             "shows a low winner count and a high contribution, which is the finding rather than a failure.")
    L.append("")
    L.append("| Source | Winner | Contributed |")
    L.append("|---|---|---|")
    for k in sorted(set(by_source) | set(by_contrib)):
        L.append(f"| {k} | {by_source.get(k, 0)} | {by_contrib.get(k, 0)} |")
    L.append("")

    L.append("## By vertical, multi-label")
    L.append("")
    L.append("| Vertical | Assets |")
    L.append("|---|---|")
    for k, n in by_vertical.most_common():
        L.append(f"| {k} | {n} |")
    L.append("")

    L.append("## By research thread")
    L.append("")
    L.append("| Thread | Assets |")
    L.append("|---|---|")
    for k, n in by_thread.most_common():
        L.append(f"| {k} | {n} |")
    L.append("")

    L.append("## Open work, by flag")
    L.append("")
    L.append("| Flag | Assets |")
    L.append("|---|---|")
    for k, n in flags.most_common():
        L.append(f"| {k} | {n} |")
    L.append("")

    os.makedirs(args.out, exist_ok=True)
    md_path = os.path.join(args.out, "FACTS.md")
    js_path = os.path.join(args.out, "facts.json")
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L) + "\n")
    with open(js_path, "w", encoding="utf-8") as fh:
        json.dump(facts, fh, indent=2)

    print("\n".join(L))
    log(f"\nfacts: {md_path}")
    log(f"json:  {js_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
